
# DSS-LVR IAF regression diagnostics

This notebook has two separate purposes:

1. **Current controlled training:** use an independent RNG for `q0.loc` jitter, isolate diagnostic sampling from the training RNG, and record how the transported posterior changes with flow depth.
2. **Historical IAF reproduction:** reproduce the original `iaf_ordering_depth_test` conditions as closely as possible, including its old RNG behavior, so changes made after that benchmark can be detected.

The historical section is intentionally isolated. Do not use its legacy RNG behavior for new experiments.

In [1]:
from pathlib import Path
import inspect
import math
import random
import sys
import time

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score
from IPython.display import display


def find_project_root():
    here = Path.cwd().resolve()
    for root in (here, *here.parents):
        if (root / "Python" / "model2.py").exists() and (root / "Python" / "bnn_metric.py").exists():
            return root
    raise FileNotFoundError("Run this notebook inside the NFlow repository.")

ROOT = find_project_root()
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

%load_ext autoreload
%autoreload 2

import Python.model2 as md
import Python.bnn_metric as metric

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DTYPE = torch.float32
HAS_SLAB_INIT = "slab_init" in inspect.signature(md.GroupedBNNVI).parameters

pd.set_option("display.max_columns", 40)
pd.set_option("display.width", 180)
print("project root :", ROOT)
print("device       :", DEVICE)
print("slab_init API:", HAS_SLAB_INIT)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
project root : D:\positron\NFlow
device       : cpu
slab_init API: True

## Current simulator

In [6]:
def simfun(
    n=600,
    p=100,
    n_active=10,
    n_true_units=10,
    activation="relu",          # "none", "relu", or "trig"
    structure="mixed",          # "axis" or "mixed"
    features_per_unit=3,        # only used for mixed
    n_interactions=0,           # 0, 1, 2, 3
    n_quadratic=0,              # 0, 1, 2, 3
    extra_scale=0.5,
    sigma2=1.0,
    target_signal_sd=1.5,
    x_low=-2.5,
    x_high=2.5,
    seed=123,
    device=None,
    dtype=torch.float32,
):
    device = torch.device("cpu") if device is None else torch.device(device)
    rng = np.random.default_rng(seed)
    gen = torch.Generator(device=device)
    gen.manual_seed(seed)

    n, p, n_active, K = int(n), int(p), int(n_active), int(n_true_units)
    n_interactions, n_quadratic = int(n_interactions), int(n_quadratic)

    if activation not in {"none", "relu", "trig"}:
        raise ValueError("activation must be 'none', 'relu', or 'trig'.")
    if structure not in {"axis", "mixed"}:
        raise ValueError("structure must be 'axis' or 'mixed'.")
    if not 0 <= n_interactions <= 3 or not 0 <= n_quadratic <= 3:
        raise ValueError("n_interactions and n_quadratic must be between 0 and 3.")

    X = float(x_low) + (float(x_high) - float(x_low)) * torch.rand(
        n, p, generator=gen, device=device, dtype=dtype
    )

    active_idx = np.sort(rng.choice(p, size=n_active, replace=False))
    active_t = torch.as_tensor(active_idx, device=device, dtype=torch.long)
    Xa = X.index_select(1, active_t)

    W = np.zeros((K, n_active), dtype=np.float32)

    if structure == "axis":
        if K < n_active:
            raise ValueError("axis requires n_true_units >= n_active.")
        supports = [{unit % n_active} for unit in range(K)]
    else:
        m = min(int(features_per_unit), n_active)
        if K * m < n_active:
            raise ValueError("mixed requires n_true_units * features_per_unit >= n_active.")

        supports = [set() for _ in range(K)]
        for pos, feature in enumerate(rng.permutation(n_active)):
            supports[pos % K].add(int(feature))
        for unit in range(K):
            while len(supports[unit]) < m:
                supports[unit].add(int(rng.integers(n_active)))

    for unit, support in enumerate(supports):
        idx = np.asarray(sorted(support), dtype=int)
        signs = rng.choice([-1.0, 1.0], size=len(idx))
        magnitude = rng.uniform(0.8, 1.2)
        W[unit, idx] = magnitude * signs / np.sqrt(len(idx))

    if activation in {"relu", "trig"}:
        bias = rng.uniform(-0.8, 0.8, size=K).astype(np.float32)
    else:
        bias = np.zeros(K, dtype=np.float32)

    amplitude = rng.uniform(0.8, 1.2, size=K).astype(np.float32)

    Wt = torch.as_tensor(W, device=device, dtype=dtype)
    bt = torch.as_tensor(bias, device=device, dtype=dtype)
    at = torch.as_tensor(amplitude, device=device, dtype=dtype)

    pre = Xa @ Wt.T - bt

    trig_functions = []
    if activation == "relu":
        hidden = F.relu(pre)
    elif activation == "trig":
        hidden = torch.empty_like(pre)
        trig_names = ("sin", "cos", "sin2", "cos2")
        for unit in range(K):
            mode = unit % 4
            z = pre[:, unit]
            if mode == 0:
                hidden[:, unit] = torch.sin(z)
            elif mode == 1:
                hidden[:, unit] = torch.cos(z)
            elif mode == 2:
                hidden[:, unit] = torch.sin(z).square()
            else:
                hidden[:, unit] = torch.cos(z).square()
            trig_functions.append(trig_names[mode])
    else:
        hidden = pre

    signal = hidden @ at

    interaction_pairs = []
    if n_interactions > 0:
        candidates = [(j, k) for j in range(n_active) for k in range(j + 1, n_active)]
        rng.shuffle(candidates)
        interaction_pairs = candidates[:n_interactions]

        for j, k in interaction_pairs:
            term = Xa[:, j] * Xa[:, k]
            term = (term - term.mean()) / term.std(unbiased=False).clamp_min(1e-8)
            signal = signal + float(extra_scale) * term

    quadratic_features = []
    if n_quadratic > 0:
        quadratic_features = rng.choice(
            n_active, size=min(n_quadratic, n_active), replace=False
        ).tolist()

        for j in quadratic_features:
            term = Xa[:, j].square()
            term = (term - term.mean()) / term.std(unbiased=False).clamp_min(1e-8)
            signal = signal + float(extra_scale) * term

    signal = signal - signal.mean()
    signal = signal * float(target_signal_sd) / signal.std(unbiased=False).clamp_min(1e-8)

    y = signal + math.sqrt(float(sigma2)) * torch.randn(
        n, generator=gen, device=device, dtype=dtype
    )

    feature_true = torch.zeros(p, device=device, dtype=dtype)
    feature_true[active_t] = 1.0

    info = {
        "sim": f"{structure}_{activation}",
        "seed": int(seed),
        "n": n,
        "p": p,
        "n_active": n_active,
        "active_idx": active_idx,
        "feature_true": feature_true.detach().cpu().numpy(),
        "n_true_units": K,
        "activation": activation,
        "structure": structure,
        "features_per_unit": 1 if structure == "axis" else int(features_per_unit),
        "teacher_supports": [
            active_idx[np.asarray(sorted(s), dtype=int)].tolist()
            for s in supports
        ],
        "trig_functions": trig_functions,
        "interaction_pairs": [
            (int(active_idx[j]), int(active_idx[k]))
            for j, k in interaction_pairs
        ],
        "quadratic_features": [
            int(active_idx[j])
            for j in quadratic_features
        ],
        "n_interactions": len(interaction_pairs),
        "n_quadratic": len(quadratic_features),
        "sigma2": float(sigma2),
        "signal_sd": float(signal.std(unbiased=False)),
    }

    return X, y, feature_true, signal, info


## Controlled trainer with flow-depth diagnostics

The production path below always uses an **independent jitter RNG**. Diagnostic draws also run inside `torch.random.fork_rng`, so changing `record_every` or `R_diag` cannot alter subsequent optimization draws.

Recorded checkpoints distinguish the base posterior (`q0_*_sd`) from the transported posterior (`post_*_sd`), and separately track all-on representation R² (`repr_r2`) versus the actually gated network (`gated_r2`).

In [3]:
def train_trace(
    X_train, y_train, X_eval, signal_eval, X_test, signal_test, *, truth,
    selection_mode="feature_group", hidden_dims=(20,), sigma2=1.0,
    init_sd=0.5, K_flow=4, flow_hidden_units=128, flow_hidden_layers=2,
    scale_clip=2.0, flow_seed=123, iaf_ordering_scheme="cyclic3",
    iaf_shuffle_within_role=True, gate_type="normalized_requ", gate_scale=1.0,
    epochs=1200, warmup_epochs=300, lr=3e-4, R_train=32, R_diag=128,
    R_final=500, record_every=100, init_loc_jitter=0.05, jitter_seed_offset=99173,
    grad_clip=5.0, support_threshold=0.5, seed=123,
    slab_init="auto", slab_sd_ratio=0.1, slab_bias_sd=0.02,
):
    random.seed(int(seed)); np.random.seed(int(seed)); torch.manual_seed(int(seed))
    if torch.cuda.is_available(): torch.cuda.manual_seed_all(int(seed))

    model_kwargs = dict(
        X=X_train, y=y_train, input_dim=X_train.shape[1], hidden_dims=tuple(hidden_dims), out_dim=1,
        selection_mode=selection_mode, family="gaussian", sigma2=float(sigma2), init_sd=float(init_sd),
        K_flow=int(K_flow), flow_type="iaf", flow_hidden_units=int(flow_hidden_units),
        flow_hidden_layers=int(flow_hidden_layers), scale_clip=float(scale_clip), flow_seed=int(flow_seed),
        iaf_ordering_scheme=iaf_ordering_scheme, iaf_shuffle_within_role=bool(iaf_shuffle_within_role),
        gate_type=gate_type, gate_scale=float(gate_scale),
    )
    if HAS_SLAB_INIT:
        model_kwargs.update(slab_init=slab_init, slab_sd_ratio=slab_sd_ratio, slab_bias_sd=slab_bias_sd)
    model = md.GroupedBNNVI(**model_kwargs).to(DEVICE)

    # Independent jitter RNG: changing K_flow no longer changes q0.loc through RNG consumption.
    if float(init_loc_jitter) > 0:
        g = torch.Generator(device=model.q0.loc.device)
        g.manual_seed(int(seed) + int(jitter_seed_offset))
        jitter = torch.randn(model.q0.loc.shape, generator=g, device=model.q0.loc.device, dtype=model.q0.loc.dtype)
        with torch.no_grad(): model.q0.loc.add_(float(init_loc_jitter) * jitter)

    init_q0_loc = model.q0.loc.detach().cpu().clone()
    init_q0_sd = torch.exp(model.q0.raw_log_scale.detach().clamp(-8.0, 2.0)).cpu().clone()
    optimizer = torch.optim.Adam(model.parameters(), lr=float(lr))
    history = []

    def record(epoch, phase):
        model.eval()
        devices = [torch.cuda.current_device()] if DEVICE.type == "cuda" else []
        with torch.random.fork_rng(devices=devices):
            torch.manual_seed(int(seed) + 700000 + int(epoch))
            if DEVICE.type == "cuda": torch.cuda.manual_seed_all(int(seed) + 700000 + int(epoch))
            with torch.no_grad():
                xi, log_q = model.sample_posterior(int(R_diag))
                s, v, t = model.decoder.split_latent(xi)
                sem = model.decoder.group_semantics(xi)
                pred_repr = model.decoder(X_eval, xi, force_all_on=True)
                pred_gated = model.decoder(X_eval, xi, force_all_on=(phase in {"init", "repr"}))
                f_repr = metric.function_metrics(signal_eval, pred_repr)
                f_gated = metric.function_metrics(signal_eval, pred_gated)
                ll = model.log_likelihood(xi, force_all_on=(phase in {"init", "repr"})).mean()
                prior = model.log_prior(xi).mean()
                q0_sd = torch.exp(model.q0.raw_log_scale.detach().clamp(-5.0, 2.0))
                row = {
                    "epoch": int(epoch), "phase": phase,
                    "repr_r2": float(f_repr["r2"]), "gated_r2": float(f_gated["r2"]),
                    "repr_mse": float(f_repr["mse"]),
                    "pred_var": float(pred_repr.var(dim=0, unbiased=False).mean()),
                    "pred_mean_sd": float(pred_repr.mean(dim=0).std(unbiased=False)),
                    "post_U_sd": float(s.std(dim=0, unbiased=False).mean()),
                    "post_V_sd": float(v.std(dim=0, unbiased=False).mean()),
                    "post_tau_sd": float(t.std(dim=0, unbiased=False).mean()),
                    "q0_U_sd": float(q0_sd[:model.decoder.s_dim].mean()),
                    "q0_V_sd": float(q0_sd[model.decoder.s_dim:model.decoder.s_dim + model.decoder.u_dim].mean()),
                    "q0_tau_sd": float(q0_sd[model.decoder.s_dim + model.decoder.u_dim:].mean()),
                    "margin_mean": float(sem["margin"].mean()), "margin_sd": float(sem["margin"].std(unbiased=False)),
                    "active_rate": float(sem["active"].float().mean()),
                    "loglik": float(ll), "logprior": float(prior), "logq": float(log_q.mean()),
                    "kl_like": float((log_q.mean() - prior)),
                }
                if model.decoder.has_feature_gates:
                    fp = model.decoder.feature_semantics(xi)["active"].float().mean(0)
                    target = torch.as_tensor(np.asarray(truth["feature_true"]) > 0.5, device=fp.device)
                    row["feature_pip_mean"] = float(fp.mean())
                    row["active_feature_pip"] = float(fp[target].mean()) if target.any() else np.nan
                    row["inactive_feature_pip"] = float(fp[~target].mean()) if (~target).any() else np.nan
                if model.decoder.has_unit_gates:
                    up = model.decoder.unit_semantics(xi)["active"].float().mean(0)
                    row["unit_pip_mean"] = float(up.mean())
                    row["expected_units"] = float(up.sum())
        history.append(row)
        print(f"epoch={epoch:04d} {phase:6s} reprR2={row['repr_r2']:+.4f} gatedR2={row['gated_r2']:+.4f} "
              f"predVar={row['pred_var']:.3g} U/V/tauSD={row['post_U_sd']:.3g}/{row['post_V_sd']:.3g}/{row['post_tau_sd']:.3g} "
              f"active={row['active_rate']:.3f}")

    record(0, "init")
    if DEVICE.type == "cuda": torch.cuda.synchronize()
    started = time.perf_counter()

    for epoch in range(1, int(epochs) + 1):
        model.train(); optimizer.zero_grad(set_to_none=True)
        warmup = epoch <= int(warmup_epochs)
        if warmup:
            xi, log_q = model.sample_posterior(int(R_train))
            elbo = model.log_likelihood(xi, force_all_on=True) + model.log_prior(xi) - log_q
        else:
            elbo = model.elbo_draws(int(R_train))["elbo"]
        (-elbo.mean()).backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), float(grad_clip))
        optimizer.step()
        if epoch == 1 or epoch % int(record_every) == 0 or epoch == int(warmup_epochs) or epoch == int(epochs):
            record(epoch, "repr" if warmup else "select")

    if DEVICE.type == "cuda": torch.cuda.synchronize()
    train_time = time.perf_counter() - started
    model.eval()
    with torch.no_grad():
        xi_final, _ = model.sample_posterior(int(R_final))
        pred_test = model.decoder(X_test, xi_final)
        fm = metric.function_metrics(signal_test, pred_test)

    result = {"mse": float(fm["mse"]), "r2": float(fm["r2"]), "train_time_sec": float(train_time)}
    feature_pip = unit_pip = None
    if model.decoder.has_feature_gates:
        feature_pip = model.decoder.feature_semantics(xi_final)["active"].float().mean(0).cpu().numpy()
        target = np.asarray(truth["feature_true"], dtype=float).reshape(-1) > 0.5
        selected = feature_pip > float(support_threshold); active, inactive = target, ~target
        ba = np.mean((1.0 - feature_pip[active]) ** 2); b0 = np.mean(feature_pip[inactive] ** 2) if inactive.any() else np.nan
        result.update(tpr=float(selected[active].mean()),
                      auroc=float(roc_auc_score(target.astype(int), feature_pip)) if np.unique(target).size == 2 else np.nan,
                      brier_bal=float(0.5 * (ba + b0)) if inactive.any() else float(ba),
                      expected_support=float(feature_pip.sum()), selected_support=int(selected.sum()),
                      mean_active_pip=float(feature_pip[active].mean()),
                      mean_inactive_pip=float(feature_pip[inactive].mean()) if inactive.any() else np.nan)
    if model.decoder.has_unit_gates:
        unit_pip = model.decoder.unit_semantics(xi_final)["active"].float().mean(0).cpu().numpy()
        result.update(expected_active_units=float(unit_pip.sum()),
                      selected_active_units=int((unit_pip > float(support_threshold)).sum()))
    if selection_mode == "feature_unit_induced_edge":
        result["network_density"] = float(metric.network_density(model.decoder, xi_final))
        result["path_density"] = float(metric.active_path_density(model.decoder, xi_final))

    return {"result": result, "history": pd.DataFrame(history), "model": model, "xi": xi_final.detach(),
            "feature_pip": feature_pip, "unit_pip": unit_pip,
            "init_q0_loc": init_q0_loc, "init_q0_sd": init_q0_sd}

In [4]:
def run_experiment(
    *, n=600, p=100, n_active=10, n_true_units=4, activation="relu", structure="mixed",
    features_per_unit=3, n_interactions=2, n_quadratic=1, extra_scale=0.5,
    target_signal_sd=1.5, sigma2=1.0, x_low=-2.5, x_high=2.5, data_seed=400,
    hidden_dims=(20, 20), selection_mode="feature_unit_induced_edge",
    K_flow=4, flow_hidden_units=128, flow_hidden_layers=2, scale_clip=2.0,
    iaf_ordering_scheme="cyclic3", iaf_shuffle_within_role=True,
    gate_type="normalized_requ", gate_scale=1.0, train_frac=0.8, diagnostic_frac=0.10,
    epochs=1200, warmup_epochs=300, lr=3e-4, R_train=32, R_diag=128, R_final=500,
    record_every=100, init_sd=0.5, init_loc_jitter=0.05, grad_clip=5.0,
    support_threshold=0.5, fit_seed=None, slab_init="auto", slab_sd_ratio=0.1, slab_bias_sd=0.02,
):
    if fit_seed is None: fit_seed = int(data_seed + 100_000 + p + 17 * len(tuple(hidden_dims)))
    X, y, feature_true, signal, info = simfun(
        n=n, p=p, n_active=n_active, n_true_units=n_true_units, activation=activation, structure=structure,
        features_per_unit=features_per_unit, n_interactions=n_interactions, n_quadratic=n_quadratic,
        extra_scale=extra_scale, sigma2=sigma2, target_signal_sd=target_signal_sd,
        x_low=x_low, x_high=x_high, seed=data_seed, device=DEVICE, dtype=DTYPE)

    rng = np.random.default_rng(int(data_seed + 123456)); idx = rng.permutation(int(n))
    n_train = int(round(float(train_frac) * int(n))); train_idx, test_idx = idx[:n_train], idx[n_train:]
    n_diag = max(1, int(round(float(diagnostic_frac) * n_train))); diag_idx = train_idx[:n_diag]
    ti = torch.as_tensor(train_idx, device=DEVICE); di = torch.as_tensor(diag_idx, device=DEVICE); te = torch.as_tensor(test_idx, device=DEVICE)

    print(f"\nExperiment\n  n/p/active : {n}/{p}/{n_active}\n  teacher    : {activation} | {structure} | {n_true_units} units"
          + (f" | {features_per_unit} features/unit" if structure == "mixed" else "")
          + f"\n  extra      : interaction={n_interactions} | quadratic={n_quadratic}"
          + f"\n  fitted BNN : {tuple(hidden_dims)} | {selection_mode}"
          + f"\n  flow       : K={K_flow} | {iaf_ordering_scheme} | slab_init={slab_init}"
          + f"\n  training   : epochs={epochs} | warmup={warmup_epochs} | R={R_train}/{R_diag}/{R_final}"
          + f"\n  seed       : data={data_seed} | fit={fit_seed}")

    out = train_trace(
        X[ti], y[ti], X[di], signal[di], X[te], signal[te], truth=info,
        selection_mode=selection_mode, hidden_dims=tuple(hidden_dims), sigma2=sigma2, init_sd=init_sd,
        K_flow=K_flow, flow_hidden_units=flow_hidden_units, flow_hidden_layers=flow_hidden_layers,
        scale_clip=scale_clip, flow_seed=int(fit_seed + 17), iaf_ordering_scheme=iaf_ordering_scheme,
        iaf_shuffle_within_role=iaf_shuffle_within_role, gate_type=gate_type, gate_scale=gate_scale,
        epochs=epochs, warmup_epochs=warmup_epochs, lr=lr, R_train=R_train, R_diag=R_diag, R_final=R_final,
        record_every=record_every, init_loc_jitter=init_loc_jitter, grad_clip=grad_clip,
        support_threshold=support_threshold, seed=fit_seed, slab_init=slab_init,
        slab_sd_ratio=slab_sd_ratio, slab_bias_sd=slab_bias_sd)
    out["data_info"] = info
    print("\nFinal result")
    display(pd.DataFrame.from_dict(out["result"], orient="index", columns=["value"]).round(6))
    return out

print("simfun, train_trace, run_experiment ready")

simfun, train_trace, run_experiment ready

## One controlled MLP run

In [18]:
exp = run_experiment(
    n=5000, p=500, n_active=10, n_true_units=4,
    activation="relu", structure="mixed", features_per_unit=3,
    n_interactions=2, n_quadratic=1,
    hidden_dims=(20, 20), selection_mode="feature_unit_induced_edge",
    K_flow=6, epochs=1200, warmup_epochs=300, record_every=100,
    data_seed=400, slab_init="auto",
)

display(exp["history"].round(4))

Experiment
  n/p/active : 5000/500/10
  teacher    : relu | mixed | 4 units | 3 features/unit
  extra      : interaction=2 | quadratic=1
  fitted BNN : (20, 20) | feature_unit_induced_edge
  flow       : K=6 | cyclic3 | slab_init=auto
  training   : epochs=1200 | warmup=300 | R=32/128/500
  seed       : data=400 | fit=100934
epoch=0000 init   reprR2=-0.0092 gatedR2=-0.0092 predVar=0.00139 U/V/tauSD=0.00772/0.495/0.473 active=0.487
epoch=0001 repr   reprR2=-0.0010 gatedR2=-0.0010 predVar=0.00131 U/V/tauSD=0.00775/0.498/0.547 active=0.521
epoch=0100 repr   reprR2=+0.6296 gatedR2=+0.6296 predVar=0.109 U/V/tauSD=0.214/0.902/0.982 active=0.514
epoch=0200 repr   reprR2=+0.5466 gatedR2=+0.5466 predVar=0.0722 U/V/tauSD=0.335/0.865/0.955 active=0.517
epoch=0300 repr   reprR2=-4.3316 gatedR2=-4.3316 predVar=1.86 U/V/tauSD=2.68/1.47/1.76 active=0.501
epoch=0400 select reprR2=-865.0767 gatedR2=+0.9385 predVar=3.5e+03 U/V/tauSD=0.804/0.663/0.104 active=0.061
epoch=0500 select reprR2=-476.8272 gatedR2=+0.7555 predVar=9.26e+03 U/V/tauSD=0.656/0.686/0.0691 active=0.048
epoch=0600 select reprR2=-7146.7310 gatedR2=+0.9322 predVar=6.07e+04 U/V/tauSD=0.946/0.73/0.0567 active=0.040
epoch=0700 select reprR2=-3066.5886 gatedR2=+0.9373 predVar=5.63e+04 U/V/tauSD=0.918/0.704/0.0438 active=0.035
epoch=0800 select reprR2=-2203.6497 gatedR2=+0.8365 predVar=1.69e+04 U/V/tauSD=0.707/0.719/0.0485 active=0.037
epoch=0900 select reprR2=-1001.0671 gatedR2=+0.9422 predVar=9.22e+04 U/V/tauSD=1.03/0.682/0.0409 active=0.033
epoch=1000 select reprR2=-3756.9216 gatedR2=+0.9427 predVar=4.17e+04 U/V/tauSD=0.871/0.699/0.0364 active=0.033
epoch=1100 select reprR2=-766.0331 gatedR2=+0.9380 predVar=3.57e+04 U/V/tauSD=0.814/0.674/0.0362 active=0.033
epoch=1200 select reprR2=-372.8559 gatedR2=+0.8892 predVar=5.48e+04 U/V/tauSD=0.925/0.673/0.0307 active=0.033

Final result

                             value
mse                       0.254952
r2                        0.887502
train_time_sec         2413.811629
tpr                       1.000000
auroc                     1.000000
brier_bal                 0.000004
expected_support         10.652000
selected_support         10.000000
mean_active_pip           1.000000
mean_inactive_pip         0.001331
expected_active_units     7.232000
selected_active_units     7.000000
network_density           0.006483
path_density              0.000575

,epoch,phase,repr_r2,gated_r2,repr_mse,pred_var,pred_mean_sd,post_U_sd,post_V_sd,post_tau_sd,q0_U_sd,q0_V_sd,q0_tau_sd,margin_mean,margin_sd,active_rate,loglik,logprior,logq,kl_like,feature_pip_mean,active_feature_pip,inactive_feature_pip,unit_pip_mean,expected_units
0,0,init,-0.0092,-0.0092,2.7381,0.0014,0.0306,0.0077,0.4949,0.4731,0.0078,0.5000,0.5000,-0.0176,0.6704,0.4870,-10132.1113,-10192.4824,36391.3555,46583.8359,0.4911,0.4867,0.4912,0.4361,17.4453
1,1,repr,-0.0010,-0.0010,2.7158,0.0013,0.0268,0.0078,0.4976,0.5470,0.0078,0.5002,0.5002,0.0368,0.7145,0.5215,-10098.5293,-10193.2988,36341.8750,46535.1719,0.5269,0.5250,0.5269,0.4537,18.1484
2,100,repr,0.6296,0.6296,1.0049,0.1092,1.1532,0.2139,0.9017,0.9823,0.0078,0.5019,0.5023,0.0391,1.4178,0.5138,-6733.3184,-13099.0947,4831.8979,17930.9922,0.5290,0.5297,0.5290,0.3240,12.9609
3,200,repr,0.5466,0.5466,1.2301,0.0722,0.9395,0.3354,0.8647,0.9547,0.0078,0.5019,0.5022,0.0894,1.4018,0.5170,-7244.1670,-13399.9092,-2023.5575,11376.3516,0.5359,0.5383,0.5358,0.2807,11.2266
4,300,repr,-4.3316,-4.3316,14.4649,1.8571,1.6672,2.6752,1.4720,1.7643,0.0078,0.5019,0.5023,-0.0096,9.2212,0.5010,-42847.4219,-767274.5000,-21501.8867,745772.6250,0.5089,0.2859,0.5135,0.4016,16.0625
5,400,select,-865.0767,0.9385,2349.6975,3498.2122,10.1239,0.8037,0.6628,0.1042,0.0078,0.5020,0.4938,-1.5441,1.0895,0.0606,-5984.4639,-16262.5254,-11617.8145,4644.7109,0.0303,1.0000,0.0105,0.4391,17.5625
6,500,select,-476.8272,0.7555,1296.3624,9258.8555,11.7176,0.6555,0.6865,0.0691,0.0078,0.5019,0.4915,-1.7736,1.0603,0.0475,-6715.7881,-14014.6797,-10326.8115,3687.8682,0.0280,1.0000,0.0082,0.2912,11.6484
7,600,select,-7146.7310,0.9322,19392.0527,60676.2812,25.2193,0.9460,0.7304,0.0567,0.0078,0.5019,0.4910,-2.1226,1.2191,0.0399,-5889.8154,-16767.5605,-14190.0703,2577.4902,0.0239,1.0000,0.0040,0.2393,9.5703
8,700,select,-3066.5886,0.9373,8322.4785,56254.4297,20.9278,0.9176,0.7042,0.0438,0.0078,0.5018,0.4897,-2.3154,1.1529,0.0350,-6018.8193,-16440.2832,-14060.8809,2379.4023,0.0217,1.0000,0.0018,0.2006,8.0234
9,800,select,-2203.6497,0.8365,5981.2944,16923.8379,11.3768,0.7068,0.7194,0.0485,0.0078,0.5017,0.4886,-2.1307,1.1306,0.0371,-6352.0903,-13696.0527,-11449.6396,2246.4131,0.0240,1.0000,0.0041,0.2012,8.0469
10,900,select,-1001.0671,0.9422,2718.6443,92175.4609,23.6198,1.0263,0.6817,0.0409,0.0079,0.5017,0.4883,-2.3129,1.1621,0.0335,-5822.7485,-16773.8281,-15314.7090,1459.1191,0.0212,1.0000,0.0012,0.1873,7.4922
11,1000,select,-3756.9216,0.9427,10195.3779,41729.6641,16.6667,0.8711,0.6985,0.0364,0.0079,0.5017,0.4865,-2.3992,1.1454,0.0328,-5835.3057,-14886.6191,-13703.1719,1183.4473,0.0212,1.0000,0.0012,0.1777,7.1094
12,1100,select,-766.0331,0.9380,2080.9888,35659.0742,23.3669,0.8140,0.6738,0.0362,0.0079,0.5016,0.4856,-2.3392,1.1197,0.0330,-5871.5269,-14401.5059,-12996.1748,1405.3311,0.0212,1.0000,0.0012,0.1801,7.2031
13,1200,select,-372.8559,0.8892,1014.2846,54832.1914,17.5170,0.9253,0.6729,0.0307,0.0079,0.5016,0.4849,-2.3228,1.1245,0.0330,-6041.9126,-15374.8633,-14340.1631,1034.7002,0.0211,1.0000,0.0011,0.1813,7.2500

In [7]:
# trig + 2 interactions
exp_trig_int = run_experiment(
    n=5000, p=500, n_active=10, n_true_units=4,
    activation="trig", structure="mixed", features_per_unit=3,
    n_interactions=2, n_quadratic=0,
    hidden_dims=(20, 20), selection_mode="feature_unit_induced_edge",
    K_flow=6, epochs=1200, warmup_epochs=300,
    R_train=32, R_diag=128, R_final=500,
    data_seed=400
)

Experiment
  n/p/active : 5000/500/10
  teacher    : trig | mixed | 4 units | 3 features/unit
  extra      : interaction=2 | quadratic=0
  fitted BNN : (20, 20) | feature_unit_induced_edge
  flow       : K=6 | cyclic3 | slab_init=auto
  training   : epochs=1200 | warmup=300 | R=32/128/500
  seed       : data=400 | fit=100934
epoch=0000 init   reprR2=-0.0028 gatedR2=-0.0028 predVar=0.00139 U/V/tauSD=0.00772/0.495/0.473 active=0.487
epoch=0001 repr   reprR2=+0.0027 gatedR2=+0.0027 predVar=0.00127 U/V/tauSD=0.00775/0.498/0.547 active=0.521
epoch=0100 repr   reprR2=+0.0157 gatedR2=+0.0157 predVar=0.423 U/V/tauSD=0.229/0.992/1.16 active=0.518
epoch=0200 repr   reprR2=+0.0950 gatedR2=+0.0950 predVar=0.0895 U/V/tauSD=0.353/0.9/1.12 active=0.496
epoch=0300 repr   reprR2=+0.1008 gatedR2=+0.1008 predVar=0.233 U/V/tauSD=0.555/0.962/0.887 active=0.483
epoch=0400 select reprR2=-130.5868 gatedR2=+0.6195 predVar=7.55e+03 U/V/tauSD=0.808/0.738/0.0705 active=0.039
epoch=0500 select reprR2=-2507.5400 gatedR2=+0.6328 predVar=2.5e+04 U/V/tauSD=0.943/0.746/0.0562 active=0.026
epoch=0600 select reprR2=-1274.0690 gatedR2=+0.6477 predVar=3.45e+04 U/V/tauSD=0.89/0.78/0.0533 active=0.024
epoch=0700 select reprR2=-6827.5547 gatedR2=+0.6340 predVar=5.26e+04 U/V/tauSD=0.896/0.748/0.0413 active=0.024
epoch=0800 select reprR2=-5920.7114 gatedR2=+0.6469 predVar=5.31e+04 U/V/tauSD=0.891/0.773/0.0468 active=0.023
epoch=0900 select reprR2=-3575.8938 gatedR2=+0.6547 predVar=7.24e+04 U/V/tauSD=0.985/0.748/0.0422 active=0.023
epoch=1000 select reprR2=-344.9859 gatedR2=+0.6469 predVar=6.16e+04 U/V/tauSD=0.9/0.738/0.0421 active=0.023
epoch=1100 select reprR2=-3058.3582 gatedR2=+0.6577 predVar=5.57e+04 U/V/tauSD=0.874/0.778/0.0415 active=0.023
epoch=1200 select reprR2=-674.1617 gatedR2=+0.6491 predVar=6.75e+04 U/V/tauSD=0.961/0.775/0.0343 active=0.023

Final result

                            value
mse                      0.833669
r2                       0.616534
train_time_sec         315.043014
tpr                      0.600000
auroc                    0.761633
brier_bal                0.200001
expected_support         6.225999
selected_support         6.000000
mean_active_pip          0.600000
mean_inactive_pip        0.000461
expected_active_units    6.134000
selected_active_units    6.000000
network_density          0.003650
path_density             0.000167

In [8]:
exp_trig_int = run_experiment(
    n=5000, p=500, n_active=10, n_true_units=4,
    activation="trig", structure="mixed", features_per_unit=3,
    n_interactions=2, n_quadratic=0,
    hidden_dims=(40, 40), selection_mode="feature_unit_induced_edge",
    K_flow=6, epochs=3000, warmup_epochs=500,
    R_train=32, R_diag=128, R_final=500,
    data_seed=400
)

Experiment
  n/p/active : 5000/500/10
  teacher    : trig | mixed | 4 units | 3 features/unit
  extra      : interaction=2 | quadratic=0
  fitted BNN : (40, 40) | feature_unit_induced_edge
  flow       : K=6 | cyclic3 | slab_init=auto
  training   : epochs=3000 | warmup=500 | R=32/128/500
  seed       : data=400 | fit=100934
epoch=0000 init   reprR2=-0.0028 gatedR2=-0.0028 predVar=0.00219 U/V/tauSD=0.00791/0.494/0.505 active=0.500
epoch=0001 repr   reprR2=+0.0129 gatedR2=+0.0129 predVar=0.00224 U/V/tauSD=0.00794/0.502/0.449 active=0.487
epoch=0100 repr   reprR2=+0.3002 gatedR2=+0.3002 predVar=0.272 U/V/tauSD=0.35/0.929/1.07 active=0.649
epoch=0200 repr   reprR2=+0.3271 gatedR2=+0.3271 predVar=0.152 U/V/tauSD=0.49/0.957/0.757 active=0.664
epoch=0300 repr   reprR2=+0.1985 gatedR2=+0.1985 predVar=0.122 U/V/tauSD=0.548/0.932/0.895 active=0.655
epoch=0400 repr   reprR2=+0.0037 gatedR2=+0.0037 predVar=0.667 U/V/tauSD=1.14/1.17/0.969 active=0.702
epoch=0500 repr   reprR2=+0.1484 gatedR2=+0.1484 predVar=0.297 U/V/tauSD=0.8/0.969/0.901 active=0.710
epoch=0600 select reprR2=-538.8578 gatedR2=+0.6179 predVar=3.92e+04 U/V/tauSD=0.865/0.76/0.0861 active=0.042
epoch=0700 select reprR2=-7306.5176 gatedR2=+0.6458 predVar=1.71e+05 U/V/tauSD=0.907/0.734/0.0646 active=0.027
epoch=0800 select reprR2=-2193.7595 gatedR2=+0.6564 predVar=1.71e+05 U/V/tauSD=0.906/0.735/0.0528 active=0.026
epoch=0900 select reprR2=-9416.8018 gatedR2=+0.6464 predVar=2.69e+05 U/V/tauSD=0.943/0.739/0.0474 active=0.026
epoch=1000 select reprR2=-3755.8484 gatedR2=+0.6582 predVar=2.28e+05 U/V/tauSD=0.931/0.744/0.046 active=0.026
epoch=1100 select reprR2=-18806.9785 gatedR2=+0.6556 predVar=2.84e+05 U/V/tauSD=0.972/0.757/0.0357 active=0.025
epoch=1200 select reprR2=-2057.0725 gatedR2=+0.6520 predVar=2.29e+05 U/V/tauSD=0.942/0.738/0.0398 active=0.025
epoch=1300 select reprR2=-6861.4722 gatedR2=+0.6568 predVar=2.84e+05 U/V/tauSD=0.946/0.744/0.0363 active=0.025
epoch=1400 select reprR2=-20871.7520 gatedR2=+0.6490 predVar=3.24e+05 U/V/tauSD=0.957/0.744/0.036 active=0.025
epoch=1500 select reprR2=-3047.2456 gatedR2=+0.6501 predVar=2.65e+05 U/V/tauSD=0.913/0.761/0.0332 active=0.025
epoch=1600 select reprR2=-898.0594 gatedR2=+0.6478 predVar=3.63e+05 U/V/tauSD=0.967/0.745/0.0333 active=0.025
epoch=1700 select reprR2=-1135.2543 gatedR2=+0.6459 predVar=3.07e+05 U/V/tauSD=0.972/0.752/0.0321 active=0.025
epoch=1800 select reprR2=-11780.7227 gatedR2=+0.6520 predVar=2.9e+05 U/V/tauSD=0.945/0.756/0.0349 active=0.025
epoch=1900 select reprR2=-49369.1953 gatedR2=+0.6519 predVar=3.41e+05 U/V/tauSD=0.964/0.756/0.0311 active=0.025
epoch=2000 select reprR2=-3787.8718 gatedR2=+0.6530 predVar=2.63e+05 U/V/tauSD=0.923/0.758/0.0306 active=0.025
epoch=2100 select reprR2=-35110.4102 gatedR2=+0.6420 predVar=3.29e+05 U/V/tauSD=0.99/0.757/0.0311 active=0.025
epoch=2200 select reprR2=-2912.4194 gatedR2=+0.6533 predVar=2.62e+05 U/V/tauSD=0.92/0.76/0.0313 active=0.025
epoch=2300 select reprR2=-7149.1001 gatedR2=+0.6438 predVar=4.05e+05 U/V/tauSD=1.01/0.751/0.0287 active=0.025
epoch=2400 select reprR2=-4407.5977 gatedR2=+0.6456 predVar=4.12e+05 U/V/tauSD=0.972/0.775/0.0293 active=0.025
epoch=2500 select reprR2=-1509.2999 gatedR2=+0.6516 predVar=3.93e+05 U/V/tauSD=0.968/0.763/0.0283 active=0.025
epoch=2600 select reprR2=-11021.7559 gatedR2=+0.6495 predVar=3.35e+05 U/V/tauSD=0.971/0.776/0.0311 active=0.025
epoch=2700 select reprR2=-1450.7347 gatedR2=+0.6511 predVar=3.1e+05 U/V/tauSD=0.967/0.788/0.0327 active=0.025
epoch=2800 select reprR2=-1189.1018 gatedR2=+0.6485 predVar=3.42e+05 U/V/tauSD=0.981/0.772/0.0309 active=0.025
epoch=2900 select reprR2=-5996.7974 gatedR2=+0.6421 predVar=3.63e+05 U/V/tauSD=0.983/0.773/0.0308 active=0.025
epoch=3000 select reprR2=-3788.4138 gatedR2=+0.6492 predVar=3.05e+05 U/V/tauSD=0.965/0.766/0.0315 active=0.025

Final result

                             value
mse                       0.798244
r2                        0.632829
train_time_sec         1847.477100
tpr                       0.600000
auroc                     0.770000
brier_bal                 0.201021
expected_support          7.158000
selected_support          7.000000
mean_active_pip           0.600000
mean_inactive_pip         0.002363
expected_active_units     7.150000
selected_active_units     7.000000
network_density           0.002266
path_density              0.000093


## Controlled K-flow comparison

Run this only after the single experiment works. All runs below share the same data, fit seed, slab initialization, and **exact same q0 jitter**. The final check reports the maximum difference between initial `q0.loc` vectors; it should be zero.

In [7]:
depth_runs = {}
for K in (3, 4, 6, 7):
    depth_runs[K] = run_experiment(
        n=600, p=100, n_active=10, n_true_units=4,
        activation="relu", structure="mixed", features_per_unit=3,
        n_interactions=2, n_quadratic=1,
        hidden_dims=(20, 20), selection_mode="feature_unit_induced_edge",
        K_flow=K, epochs=1200, warmup_epochs=300, record_every=100,
        data_seed=400, fit_seed=100534, slab_init="auto",
    )

base = depth_runs[3]["init_q0_loc"]
print("max initial q0.loc difference vs K=3:")
for K, out in depth_runs.items():
    print(f"  K={K}: {(out['init_q0_loc'] - base).abs().max().item():.3e}")

summary = pd.DataFrame({K: out["result"] for K, out in depth_runs.items()}).T
summary.index.name = "K_flow"
display(summary.round(4))

trace = pd.concat([out["history"].assign(K_flow=K) for K, out in depth_runs.items()], ignore_index=True)
display(trace[["K_flow", "epoch", "phase", "repr_r2", "gated_r2", "pred_var", "q0_U_sd", "post_U_sd",
               "post_V_sd", "post_tau_sd", "margin_mean", "active_rate", "feature_pip_mean", "unit_pip_mean"]].round(4))

Experiment
  n/p/active : 600/100/10
  teacher    : relu | mixed | 4 units | 3 features/unit
  extra      : interaction=2 | quadratic=1
  fitted BNN : (20, 20) | feature_unit_induced_edge
  flow       : K=3 | cyclic3 | slab_init=auto
  training   : epochs=1200 | warmup=300 | R=32/128/500
  seed       : data=400 | fit=100534
epoch=0000 init   reprR2=-0.1839 gatedR2=-0.1839 predVar=0.000677 U/V/tauSD=0.017/0.498/0.493 active=0.478
epoch=0001 repr   reprR2=-0.1758 gatedR2=-0.1758 predVar=0.00067 U/V/tauSD=0.0171/0.492/0.491 active=0.501
epoch=0100 repr   reprR2=+0.6117 gatedR2=+0.6117 predVar=0.574 U/V/tauSD=0.257/1.02/1.11 active=0.544
epoch=0200 repr   reprR2=+0.5047 gatedR2=+0.5047 predVar=0.482 U/V/tauSD=0.51/0.963/1.26 active=0.608
epoch=0300 repr   reprR2=+0.4650 gatedR2=+0.4650 predVar=0.622 U/V/tauSD=0.645/0.967/0.92 active=0.582
epoch=0400 select reprR2=-111.3441 gatedR2=-0.1439 predVar=9.55e+03 U/V/tauSD=0.884/0.957/0.601 active=0.422
epoch=0500 select reprR2=-623.0570 gatedR2=-0.1330 predVar=1.78e+04 U/V/tauSD=0.928/0.965/0.664 active=0.389
epoch=0600 select reprR2=-35.2612 gatedR2=-0.1383 predVar=1.79e+04 U/V/tauSD=0.948/0.976/0.666 active=0.407
epoch=0700 select reprR2=-698.6786 gatedR2=-0.1340 predVar=1.64e+04 U/V/tauSD=0.938/0.964/0.646 active=0.388
epoch=0800 select reprR2=-54.0834 gatedR2=-0.1359 predVar=2.34e+04 U/V/tauSD=0.972/1/0.645 active=0.418
epoch=0900 select reprR2=-667.7379 gatedR2=-0.1352 predVar=1.77e+04 U/V/tauSD=0.964/0.984/0.605 active=0.353
epoch=1000 select reprR2=-149.4318 gatedR2=-0.1395 predVar=1.9e+04 U/V/tauSD=0.965/0.966/0.612 active=0.276
epoch=1100 select reprR2=-174.6117 gatedR2=-0.1404 predVar=1.77e+04 U/V/tauSD=0.968/0.97/0.608 active=0.369
epoch=1200 select reprR2=-58.6894 gatedR2=-0.1298 predVar=1.74e+04 U/V/tauSD=0.952/0.963/0.609 active=0.318

Final result

                           value
mse                     2.078776
r2                     -0.000372
train_time_sec         39.451262
tpr                     0.200000
auroc                   0.262778
brier_bal               0.268876
expected_support       49.675999
selected_support       47.000000
mean_active_pip         0.466400
mean_inactive_pip       0.500133
expected_active_units   0.182000
selected_active_units   0.000000
network_density         0.002225
path_density            0.000025

Experiment
  n/p/active : 600/100/10
  teacher    : relu | mixed | 4 units | 3 features/unit
  extra      : interaction=2 | quadratic=1
  fitted BNN : (20, 20) | feature_unit_induced_edge
  flow       : K=4 | cyclic3 | slab_init=auto
  training   : epochs=1200 | warmup=300 | R=32/128/500
  seed       : data=400 | fit=100534
epoch=0000 init   reprR2=-0.1839 gatedR2=-0.1839 predVar=0.000677 U/V/tauSD=0.017/0.498/0.493 active=0.478
epoch=0001 repr   reprR2=-0.1737 gatedR2=-0.1737 predVar=0.000676 U/V/tauSD=0.0171/0.492/0.491 active=0.500
epoch=0100 repr   reprR2=+0.4823 gatedR2=+0.4823 predVar=0.738 U/V/tauSD=0.282/0.82/0.965 active=0.487
epoch=0200 repr   reprR2=+0.5310 gatedR2=+0.5310 predVar=0.556 U/V/tauSD=0.639/0.978/1.12 active=0.529
epoch=0300 repr   reprR2=+0.5069 gatedR2=+0.5069 predVar=0.832 U/V/tauSD=0.752/0.985/0.968 active=0.514
epoch=0400 select reprR2=-14.3257 gatedR2=+0.5508 predVar=873 U/V/tauSD=0.826/0.715/0.139 active=0.726
epoch=0500 select reprR2=-771.6970 gatedR2=+0.4786 predVar=9.91e+03 U/V/tauSD=0.915/0.797/0.139 active=0.743
epoch=0600 select reprR2=-1491.9131 gatedR2=+0.5354 predVar=1.58e+04 U/V/tauSD=0.919/0.8/0.141 active=0.743
epoch=0700 select reprR2=-169.7784 gatedR2=+0.5235 predVar=1.18e+04 U/V/tauSD=0.884/0.774/0.148 active=0.743
epoch=0800 select reprR2=-43.6224 gatedR2=+0.5022 predVar=1.99e+04 U/V/tauSD=0.936/0.807/0.159 active=0.744
epoch=0900 select reprR2=-78.3088 gatedR2=+0.5413 predVar=1.4e+04 U/V/tauSD=0.915/0.798/0.142 active=0.742
epoch=1000 select reprR2=-27.4865 gatedR2=+0.5298 predVar=1.39e+04 U/V/tauSD=0.915/0.801/0.159 active=0.744
epoch=1100 select reprR2=-855.6090 gatedR2=+0.5444 predVar=1.52e+04 U/V/tauSD=0.876/0.793/0.155 active=0.744
epoch=1200 select reprR2=-441.6878 gatedR2=+0.5688 predVar=1.63e+04 U/V/tauSD=0.908/0.801/0.147 active=0.743

Final result

                            value
mse                      1.515688
r2                       0.270603
train_time_sec          47.736421
tpr                      1.000000
auroc                    0.677778
brier_bal                0.498648
expected_support        99.878006
selected_support       100.000000
mean_active_pip          1.000000
mean_inactive_pip        0.998645
expected_active_units    4.206000
selected_active_units    4.000000
network_density          0.091904
path_density             0.011032

Experiment
  n/p/active : 600/100/10
  teacher    : relu | mixed | 4 units | 3 features/unit
  extra      : interaction=2 | quadratic=1
  fitted BNN : (20, 20) | feature_unit_induced_edge
  flow       : K=6 | cyclic3 | slab_init=auto
  training   : epochs=1200 | warmup=300 | R=32/128/500
  seed       : data=400 | fit=100534
epoch=0000 init   reprR2=-0.1839 gatedR2=-0.1839 predVar=0.000677 U/V/tauSD=0.017/0.498/0.493 active=0.478
epoch=0001 repr   reprR2=-0.1687 gatedR2=-0.1687 predVar=0.000682 U/V/tauSD=0.0171/0.493/0.492 active=0.501
epoch=0100 repr   reprR2=+0.5748 gatedR2=+0.5748 predVar=0.379 U/V/tauSD=0.414/0.864/1.07 active=0.281
epoch=0200 repr   reprR2=+0.5035 gatedR2=+0.5035 predVar=0.465 U/V/tauSD=0.714/0.991/0.978 active=0.377
epoch=0300 repr   reprR2=+0.5740 gatedR2=+0.5740 predVar=0.44 U/V/tauSD=0.791/0.974/0.956 active=0.381
epoch=0400 select reprR2=-70.1348 gatedR2=+0.6464 predVar=663 U/V/tauSD=0.804/0.615/0.0857 active=0.273
epoch=0500 select reprR2=-2410.6858 gatedR2=+0.7042 predVar=7.09e+03 U/V/tauSD=0.893/0.559/0.0681 active=0.192
epoch=0600 select reprR2=-30.2999 gatedR2=+0.6800 predVar=8.48e+03 U/V/tauSD=0.867/0.578/0.0548 active=0.183
epoch=0700 select reprR2=-129.2595 gatedR2=+0.6554 predVar=5.22e+03 U/V/tauSD=0.799/0.596/0.0586 active=0.198
epoch=0800 select reprR2=-1120.2296 gatedR2=+0.7119 predVar=2.15e+04 U/V/tauSD=0.963/0.554/0.0516 active=0.183
epoch=0900 select reprR2=-663.9374 gatedR2=+0.7116 predVar=1.28e+04 U/V/tauSD=0.933/0.57/0.0483 active=0.177
epoch=1000 select reprR2=-208.7695 gatedR2=+0.5835 predVar=1.66e+04 U/V/tauSD=0.969/0.572/0.0492 active=0.178
epoch=1100 select reprR2=-1552.9799 gatedR2=+0.7282 predVar=1.69e+04 U/V/tauSD=0.935/0.562/0.0473 active=0.179
epoch=1200 select reprR2=-55.4608 gatedR2=+0.7285 predVar=1.53e+04 U/V/tauSD=0.943/0.56/0.0445 active=0.176

Final result

                           value
mse                     0.877006
r2                      0.577957
train_time_sec         70.339810
tpr                     1.000000
auroc                   0.977778
brier_bal               0.035282
expected_support       21.034000
selected_support       16.000000
mean_active_pip         1.000000
mean_inactive_pip       0.122600
expected_active_units   3.510000
selected_active_units   3.000000
network_density         0.022260
path_density            0.001413

Experiment
  n/p/active : 600/100/10
  teacher    : relu | mixed | 4 units | 3 features/unit
  extra      : interaction=2 | quadratic=1
  fitted BNN : (20, 20) | feature_unit_induced_edge
  flow       : K=7 | cyclic3 | slab_init=auto
  training   : epochs=1200 | warmup=300 | R=32/128/500
  seed       : data=400 | fit=100534
epoch=0000 init   reprR2=-0.1839 gatedR2=-0.1839 predVar=0.000677 U/V/tauSD=0.017/0.498/0.493 active=0.478
epoch=0001 repr   reprR2=-0.1670 gatedR2=-0.1670 predVar=0.00069 U/V/tauSD=0.0171/0.494/0.492 active=0.501
epoch=0100 repr   reprR2=+0.4662 gatedR2=+0.4662 predVar=0.573 U/V/tauSD=0.452/0.881/0.978 active=0.396
epoch=0200 repr   reprR2=+0.0837 gatedR2=+0.0837 predVar=1.04 U/V/tauSD=0.642/0.999/1.07 active=0.374
epoch=0300 repr   reprR2=+0.5417 gatedR2=+0.5417 predVar=0.507 U/V/tauSD=0.89/1.01/1.02 active=0.524
epoch=0400 select reprR2=-24.4261 gatedR2=+0.6112 predVar=1.06e+03 U/V/tauSD=0.887/0.557/0.115 active=0.364
epoch=0500 select reprR2=-892.7213 gatedR2=+0.6360 predVar=6.29e+03 U/V/tauSD=0.904/0.516/0.0716 active=0.258
epoch=0600 select reprR2=-70.3742 gatedR2=+0.6585 predVar=1.52e+04 U/V/tauSD=0.96/0.503/0.0515 active=0.242
epoch=0700 select reprR2=-63.9799 gatedR2=+0.6527 predVar=2.01e+04 U/V/tauSD=0.982/0.498/0.0541 active=0.240
epoch=0800 select reprR2=-2077.1377 gatedR2=+0.6336 predVar=1.42e+04 U/V/tauSD=0.917/0.521/0.0471 active=0.230
epoch=0900 select reprR2=-219.8657 gatedR2=+0.6499 predVar=1.2e+04 U/V/tauSD=0.955/0.503/0.0461 active=0.212
epoch=1000 select reprR2=-697.9897 gatedR2=+0.6529 predVar=1.52e+04 U/V/tauSD=0.928/0.513/0.0482 active=0.215
epoch=1100 select reprR2=-172.1780 gatedR2=+0.6334 predVar=1.39e+04 U/V/tauSD=0.936/0.51/0.0448 active=0.214
epoch=1200 select reprR2=-322.6494 gatedR2=+0.6344 predVar=1.43e+04 U/V/tauSD=0.94/0.517/0.0446 active=0.208

Final result

                           value
mse                     1.023752
r2                      0.507338
train_time_sec         76.447243
tpr                     1.000000
auroc                   0.955556
brier_bal               0.053289
expected_support       24.715998
selected_support       20.000000
mean_active_pip         1.000000
mean_inactive_pip       0.163511
expected_active_units   4.262000
selected_active_units   4.000000
network_density         0.034154
path_density            0.002164

max initial q0.loc difference vs K=3:
  K=3: 0.000e+00
  K=4: 0.000e+00
  K=6: 0.000e+00
  K=7: 0.000e+00

,mse,r2,train_time_sec,tpr,auroc,brier_bal,expected_support,selected_support,mean_active_pip,mean_inactive_pip,expected_active_units,selected_active_units,network_density,path_density
K_flow,,,,,,,,,,,,,,
3,2.0788,-0.0004,39.4513,0.2,0.2628,0.2689,49.676,47.0,0.4664,0.5001,0.182,0.0,0.0022,0.0000
4,1.5157,0.2706,47.7364,1.0,0.6778,0.4986,99.878,100.0,1.0000,0.9986,4.206,4.0,0.0919,0.0110
6,0.8770,0.5780,70.3398,1.0,0.9778,0.0353,21.034,16.0,1.0000,0.1226,3.510,3.0,0.0223,0.0014
7,1.0238,0.5073,76.4472,1.0,0.9556,0.0533,24.716,20.0,1.0000,0.1635,4.262,4.0,0.0342,0.0022

    K_flow  epoch   phase    repr_r2  gated_r2    pred_var  q0_U_sd  post_U_sd  post_V_sd  post_tau_sd  margin_mean  active_rate  feature_pip_mean  unit_pip_mean
0        3      0    init    -0.1839   -0.1839      0.0007   0.0171     0.0170     0.4976       0.4926      -0.0123       0.4776            0.4870         0.4541
1        3      1    repr    -0.1758   -0.1758      0.0007   0.0172     0.0171     0.4916       0.4907       0.0001       0.5013            0.5143         0.4688
2        3    100    repr     0.6117    0.6117      0.5740   0.0173     0.2569     1.0160       1.1122       0.1552       0.5441            0.6315         0.3258
3        3    200    repr     0.5047    0.5047      0.4815   0.0173     0.5102     0.9631       1.2581       0.3636       0.6081            0.7743         0.1928
4        3    300    repr     0.4650    0.4650      0.6217   0.0173     0.6448     0.9669       0.9202       0.3109       0.5815            0.7542         0.1498
5        3    400  select  -111.3441   -0.1439   9547.5117   0.0174     0.8842     0.9572       0.6010      -0.5220       0.4223            0.5892         0.0049
6        3    500  select  -623.0570   -0.1330  17760.5059   0.0174     0.9284     0.9652       0.6644      -0.6706       0.3888            0.5423         0.0051
7        3    600  select   -35.2612   -0.1383  17870.2129   0.0174     0.9479     0.9760       0.6658      -0.6249       0.4072            0.5683         0.0045
8        3    700  select  -698.6786   -0.1340  16427.3027   0.0174     0.9375     0.9637       0.6456      -0.7082       0.3877            0.5399         0.0070
9        3    800  select   -54.0834   -0.1359  23375.0957   0.0175     0.9721     0.9997       0.6455      -0.6607       0.4179            0.5843         0.0020
10       3    900  select  -667.7379   -0.1352  17719.9941   0.0175     0.9636     0.9835       0.6050      -0.8794       0.3529            0.4931         0.0023
11       3   1000  select  -149.4318   -0.1395  18981.1445   0.0175     0.9651     0.9662       0.6119      -1.1308       0.2757            0.3853         0.0016
12       3   1100  select  -174.6117   -0.1404  17742.0449   0.0175     0.9683     0.9703       0.6085      -0.7895       0.3688            0.5150         0.0033
13       3   1200  select   -58.6894   -0.1298  17449.8984   0.0176     0.9523     0.9630       0.6094      -0.8620       0.3180            0.4435         0.0041
14       4      0    init    -0.1839   -0.1839      0.0007   0.0171     0.0170     0.4976       0.4926      -0.0123       0.4776            0.4870         0.4541
15       4      1    repr    -0.1737   -0.1737      0.0007   0.0172     0.0171     0.4923       0.4913      -0.0026       0.5001            0.5135         0.4664
16       4    100    repr     0.4823    0.4823      0.7381   0.0173     0.2819     0.8197       0.9652      -0.0394       0.4866            0.4777         0.5088
17       4    200    repr     0.5310    0.5310      0.5557   0.0173     0.6391     0.9776       1.1211       0.0901       0.5291            0.5705         0.4256
18       4    300    repr     0.5069    0.5069      0.8317   0.0173     0.7520     0.9848       0.9678       0.0435       0.5136            0.5196         0.4986
19       4    400  select   -14.3257    0.5508    873.2422   0.0173     0.8256     0.7149       0.1394       1.0521       0.7259            0.9648         0.1287
20       4    500  select  -771.6970    0.4786   9911.1875   0.0173     0.9148     0.7975       0.1393       1.6808       0.7429            0.9972         0.1070
21       4    600  select -1491.9131    0.5354  15849.9648   0.0174     0.9186     0.7999       0.1410       1.7202       0.7428            0.9974         0.1063
22       4    700  select  -169.7784    0.5235  11805.2891   0.0174     0.8844     0.7742       0.1478       1.8589       0.7429            0.9984         0.1041
23       4    800  select   -43.6224    0.5022  19935.6738   0.0174     0.9358     0.8075       0.1593       1.9912       0.7444            0.9991         0.1074
24       4    900  select   -78.3088    0.5413  14000.5869   0.0174     0.9151     0.7981       0.1422       1.7882       0.7422            0.9981         0.1025
25       4   1000  select   -27.4865    0.5298  13901.8545   0.0174     0.9153     0.8012       0.1593       1.9368       0.7442            0.9992         0.1066
26       4   1100  select  -855.6090    0.5444  15209.9268   0.0174     0.8762     0.7926       0.1545       1.8488       0.7441            0.9986         0.1078
27       4   1200  select  -441.6878    0.5688  16324.6953   0.0174     0.9077     0.8007       0.1474       1.8744       0.7435            0.9989         0.1049
28       6      0    init    -0.1839   -0.1839      0.0007   0.0171     0.0170     0.4976       0.4926      -0.0123       0.4776            0.4870         0.4541
29       6      1    repr    -0.1687   -0.1687      0.0007   0.0172     0.0171     0.4929       0.4917      -0.0001       0.5011            0.5138         0.4693
30       6    100    repr     0.5748    0.5748      0.3789   0.0173     0.4136     0.8637       1.0727      -0.8072       0.2809            0.2601         0.3328
31       6    200    repr     0.5035    0.5035      0.4654   0.0173     0.7141     0.9907       0.9775      -0.4465       0.3765            0.3709         0.3906
32       6    300    repr     0.5740    0.5740      0.4397   0.0173     0.7905     0.9742       0.9559      -0.4307       0.3810            0.3880         0.3637
33       6    400  select   -70.1348    0.6464    663.4339   0.0173     0.8036     0.6155       0.0857      -0.4235       0.2733            0.2973         0.2135
34       6    500  select -2410.6858    0.7042   7091.0117   0.0173     0.8926     0.5587       0.0681      -0.7588       0.1924            0.2305         0.0969
35       6    600  select   -30.2999    0.6800   8476.1738   0.0174     0.8670     0.5775       0.0548      -0.8538       0.1830            0.2209         0.0881
36       6    700  select  -129.2595    0.6554   5216.4741   0.0174     0.7995     0.5956       0.0586      -0.7652       0.1982            0.2358         0.1041
37       6    800  select -1120.2296    0.7119  21510.9844   0.0174     0.9634     0.5537       0.0516      -0.7908       0.1835            0.2223         0.0865
38       6    900  select  -663.9374    0.7116  12774.2881   0.0174     0.9328     0.5703       0.0483      -0.8304       0.1772            0.2119         0.0906
39       6   1000  select  -208.7695    0.5835  16645.4766   0.0174     0.9690     0.5723       0.0492      -0.8502       0.1783            0.2155         0.0855
40       6   1100  select -1552.9799    0.7282  16945.9805   0.0174     0.9354     0.5625       0.0473      -0.8139       0.1795            0.2148         0.0910
41       6   1200  select   -55.4608    0.7285  15261.9248   0.0174     0.9430     0.5603       0.0445      -0.8404       0.1763            0.2113         0.0889
42       7      0    init    -0.1839   -0.1839      0.0007   0.0171     0.0170     0.4976       0.4926      -0.0123       0.4776            0.4870         0.4541
43       7      1    repr    -0.1670   -0.1670      0.0007   0.0172     0.0171     0.4935       0.4922      -0.0009       0.5006            0.5131         0.4693
44       7    100    repr     0.4662    0.4662      0.5727   0.0173     0.4517     0.8805       0.9780      -0.3385       0.3955            0.3736         0.4504
45       7    200    repr     0.0837    0.0837      1.0407   0.0173     0.6415     0.9989       1.0685      -0.4750       0.3744            0.3677         0.3910
46       7    300    repr     0.5417    0.5417      0.5067   0.0173     0.8900     1.0130       1.0177       0.0783       0.5243            0.5183         0.5393
47       7    400  select   -24.4261    0.6112   1062.1334   0.0173     0.8871     0.5568       0.1148      -0.1904       0.3642            0.4422         0.1691
48       7    500  select  -892.7213    0.6360   6285.0425   0.0173     0.9038     0.5160       0.0716      -0.5308       0.2584            0.3024         0.1482
49       7    600  select   -70.3742    0.6585  15236.0908   0.0174     0.9598     0.5031       0.0515      -0.5975       0.2420            0.2837         0.1377
50       7    700  select   -63.9799    0.6527  20065.8418   0.0174     0.9823     0.4985       0.0541      -0.5604       0.2403            0.2812         0.1383
51       7    800  select -2077.1377    0.6336  14243.2344   0.0174     0.9166     0.5209       0.0471      -0.6445       0.2300            0.2685         0.1338
52       7    900  select  -219.8657    0.6499  11969.9717   0.0174     0.9555     0.5033       0.0461      -0.6959       0.2116            0.2526         0.1090
53       7   1000  select  -697.9897    0.6529  15189.0234   0.0174     0.9281     0.5126       0.0482      -0.6962       0.2155            0.2591         0.1064
54       7   1100  select  -172.1780    0.6334  13914.6885   0.0175     0.9357     0.5101       0.0448      -0.7071       0.2143            0.2569         0.1080
55       7   1200  select  -322.6494    0.6344  14315.0908   0.0175     0.9396     0.5170       0.0446      -0.7314       0.2083            0.2486         0.1074


# Historical IAF ordering/depth regression test

This section reproduces the original `iaf_ordering_depth_test` setup:

- `n=240`, `p=6`, active features `(0, 3)`
- 2-unit ReLU teacher, fitted shallow network `(5,)`
- 60/20/20 split, data seed 123, fit/flow seed 133
- 2000 epochs, 500 warmup, `R_train=100`, `R_eval=500`, `R_final=5000`
- `scale_clip=1.5`, legacy slab initialization

**Important:** the historical trainer below intentionally uses the old global-RNG jitter and lets evaluation draws consume training RNG. This is only for regression against the old notebook; current experiments above must keep the controlled RNG behavior.

In [8]:
import Python.config as cfg
import Python.utils as ut
import Python.simfun as old_sim

HIST_SEED = 123
X_old, y_old, feature_true_old, unit_true_old, signal_old, info_old = old_sim.simfun_grouped_bnn(
    n=240, p=6, active_features=(0, 3), n_true_units=2, fit_units=5,
    repu_power=None, sigma2=1.0, target_signal_sd=1.5, seed=HIST_SEED, device=DEVICE)

split_cfg = cfg.SplitConfig(train_frac=0.60, val_frac=0.20, test_frac=0.20, seed=HIST_SEED + 1000)
indices = ut.make_split(X_old.shape[0], split_cfg)
splits_old = ut.split_data(X_old, y_old, indices, mode="tensor")
signal_old_split = ut.split_data(X_old, signal_old, indices, mode="tensor")

print("active features:", info_old["active_idx"].tolist())
print("train/val/test:", len(indices["train"]), len(indices["val"]), len(indices["test"]))

active features: [0, 3]
train/val/test: 144 48 48

In [9]:
def train_historical_iaf(K_flow, ordering_scheme):
    # Deliberately mirrors the old training RNG behavior.
    seed = HIST_SEED + 10
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)
    if torch.cuda.is_available(): torch.cuda.manual_seed_all(seed)

    kwargs = dict(
        X=splits_old["X_train"], y=splits_old["y_train"], input_dim=6, hidden_dims=(5,), out_dim=1,
        selection_mode="feature_group", family=info_old["family"], sigma2=info_old["sigma2"], init_sd=0.5,
        K_flow=int(K_flow), flow_type="iaf", flow_hidden_units=128, flow_hidden_layers=2, scale_clip=1.5,
        flow_seed=seed, iaf_ordering_scheme=ordering_scheme, iaf_shuffle_within_role=True,
        gate_type="normalized_requ", gate_scale=1.0)
    if HAS_SLAB_INIT: kwargs.update(slab_init="legacy")
    model = md.GroupedBNNVI(**kwargs).to(DEVICE)

    # Historical behavior: jitter uses the global RNG after K flow layers have been constructed.
    with torch.no_grad(): model.q0.loc.add_(0.05 * torch.randn_like(model.q0.loc))
    optimizer = torch.optim.Adam(model.parameters(), lr=3e-4)
    history = []
    if DEVICE.type == "cuda": torch.cuda.synchronize()
    started = time.perf_counter()

    for epoch in range(1, 2001):
        model.train(); optimizer.zero_grad(set_to_none=True); warmup = epoch <= 500
        if warmup:
            xi, log_q = model.sample_posterior(100)
            elbo = model.log_likelihood(xi, force_all_on=True) + model.log_prior(xi) - log_q
        else:
            elbo = model.elbo_draws(100)["elbo"]
        (-elbo.mean()).backward(); torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0); optimizer.step()

        if epoch == 1 or epoch % 500 == 0:
            model.eval()
            # Historical behavior: no fork_rng; evaluation advances the training RNG.
            with torch.no_grad():
                xi_eval, _ = model.sample_posterior(500)
                pred = model.decoder(splits_old["X_val"], xi_eval, force_all_on=warmup)
                fm = metric.function_metrics(signal_old_split["y_val"], pred)
            history.append({"epoch": epoch, "phase": "repr" if warmup else "select", "mse": fm["mse"], "r2": fm["r2"]})
            print(f"epoch={epoch:04d} phase={'repr' if warmup else 'select':6s} valMSE={fm['mse']:.5f} valR2={fm['r2']:.4f}")

    if DEVICE.type == "cuda": torch.cuda.synchronize()
    train_time = time.perf_counter() - started
    model.eval()
    with torch.no_grad(): xi_final, _ = model.sample_posterior(5000)
    metrics = metric.evaluate_bnn(model.decoder, xi_final, splits_old["X_test"], signal_old_split["y_test"], info_old)
    result = {"MSE": metrics["mse"], "R2": metrics["r2"], "AUROC": metrics.get("auroc", np.nan),
              "AUPRC": metrics.get("auprc", np.nan), "train_s": train_time}
    orders = model.flow.ordering_summary() if hasattr(model.flow, "ordering_summary") else None
    if orders is not None:
        result["orders"] = " | ".join("<".join(x["role_order"]) for x in orders)
    return {"result": result, "history": pd.DataFrame(history), "model": model, "xi": xi_final}

In [10]:
historical_targets = pd.DataFrame([
    {"configuration": "1L tau-last", "MSE": 0.0564, "R2": 0.9805, "AUROC": 1.0, "AUPRC": 1.0},
    {"configuration": "6L six permutations", "MSE": 0.0553, "R2": 0.9809, "AUROC": 1.0, "AUPRC": 1.0},
    {"configuration": "4L cyclic + tau-last", "MSE": 0.0491, "R2": 0.9830, "AUROC": 1.0, "AUPRC": 1.0},
    {"configuration": "6L two 3-layer cycles", "MSE": 0.0536, "R2": 0.9815, "AUROC": 1.0, "AUPRC": 1.0},
]).set_index("configuration")
print("Historical target from the original notebook")
display(historical_targets)

flow_specs_old = {
    "1L tau-last": (1, "cyclic3"),
    "6L six permutations": (6, "six_permutations"),
    "4L cyclic + tau-last": (4, "cyclic3"),
    "6L two 3-layer cycles": (6, "cyclic3"),
}

historical_runs = {label: train_historical_iaf(K, scheme) for label, (K, scheme) in flow_specs_old.items()}
rerun = pd.DataFrame({label: out["result"] for label, out in historical_runs.items()}).T
rerun.index.name = "configuration"
print("Current code under historical experimental conditions")
display(rerun.round(4))

comparison = historical_targets.join(rerun[["MSE", "R2", "AUROC", "AUPRC"]], lsuffix="_old", rsuffix="_now")
comparison["dR2"] = comparison["R2_now"] - comparison["R2_old"]
comparison["dMSE"] = comparison["MSE_now"] - comparison["MSE_old"]
print("Regression difference")
display(comparison.round(4))

Historical target from the original notebook

                          MSE      R2  AUROC  AUPRC
configuration
1L tau-last            0.0564  0.9805    1.0    1.0
6L six permutations    0.0553  0.9809    1.0    1.0
4L cyclic + tau-last   0.0491  0.9830    1.0    1.0
6L two 3-layer cycles  0.0536  0.9815    1.0    1.0

epoch=0001 phase=repr   valMSE=3.91310 valR2=-1.0134
epoch=0500 phase=repr   valMSE=0.04511 valR2=0.9768
epoch=1000 phase=select valMSE=0.02759 valR2=0.9858
epoch=1500 phase=select valMSE=0.04431 valR2=0.9772
epoch=2000 phase=select valMSE=0.03678 valR2=0.9811
epoch=0001 phase=repr   valMSE=4.56581 valR2=-1.3492
epoch=0500 phase=repr   valMSE=0.04169 valR2=0.9786
epoch=1000 phase=select valMSE=0.04039 valR2=0.9792
epoch=1500 phase=select valMSE=0.03171 valR2=0.9837
epoch=2000 phase=select valMSE=0.03177 valR2=0.9837
epoch=0001 phase=repr   valMSE=4.39348 valR2=-1.2605
epoch=0500 phase=repr   valMSE=0.05089 valR2=0.9738
epoch=1000 phase=select valMSE=0.03088 valR2=0.9841
epoch=1500 phase=select valMSE=0.03150 valR2=0.9838
epoch=2000 phase=select valMSE=0.03029 valR2=0.9844
epoch=0001 phase=repr   valMSE=4.56735 valR2=-1.3500
epoch=0500 phase=repr   valMSE=0.04001 valR2=0.9794
epoch=1000 phase=select valMSE=0.02908 valR2=0.9850
epoch=1500 phase=select valMSE=0.03105 valR2=0.9840
epoch=2000 phase=select valMSE=0.02960 valR2=0.9848
Current code under historical experimental conditions

                            MSE        R2 AUROC AUPRC    train_s                                             orders
configuration
1L tau-last             0.05634  0.980536   1.0   1.0  13.784161                                            U<V<tau
6L six permutations    0.054554  0.981153   1.0   1.0  36.929147  U<V<tau | V<tau<U | tau<U<V | V<U<tau | U<tau<...
4L cyclic + tau-last   0.046418  0.983964   1.0   1.0  27.396563              U<V<tau | V<tau<U | tau<U<V | U<V<tau
6L two 3-layer cycles  0.052303  0.981931   1.0   1.0  38.464738  U<V<tau | V<tau<U | tau<U<V | U<V<tau | V<tau<...

Regression difference

                       MSE_old  R2_old  AUROC_old  AUPRC_old   MSE_now    R2_now AUROC_now AUPRC_now       dR2      dMSE
configuration
1L tau-last             0.0564  0.9805        1.0        1.0   0.05634  0.980536       1.0       1.0  0.000036  -0.00006
6L six permutations     0.0553  0.9809        1.0        1.0  0.054554  0.981153       1.0       1.0  0.000253 -0.000746
4L cyclic + tau-last    0.0491  0.9830        1.0        1.0  0.046418  0.983964       1.0       1.0  0.000964 -0.002682
6L two 3-layer cycles   0.0536  0.9815        1.0        1.0  0.052303  0.981931       1.0       1.0  0.000431 -0.001297


## Optional: recover the original MCMC posterior metrics

The historical target table also contained Active SKL and Zero JS. Those require the original MCMC reference and are much more expensive. Only run the next cell after the VI-only R²/MSE regression above is close to the historical benchmark.

In [ ]:
RUN_MCMC_REFERENCE = False

if RUN_MCMC_REFERENCE:
    import Python.bnn_mcmc as mcmc
    reference_kwargs = dict(
        X=splits_old["X_train"], y=splits_old["y_train"], input_dim=6, hidden_dims=(5,), out_dim=1,
        selection_mode="feature_group", family=info_old["family"], sigma2=info_old["sigma2"],
        init_sd=0.5, K_flow=0, flow_type="meanfield", gate_type="normalized_requ", gate_scale=1.0)
    if HAS_SLAB_INIT: reference_kwargs.update(slab_init="legacy")
    reference_model = md.GroupedBNNVI(**reference_kwargs).to(DEVICE)
    reference = mcmc.run_bnn_mcmc_chains(reference_model, seed=HIST_SEED + 5000, initial_state="prior",
                                          n_chains=8, N=20000, burnin=4000, thin=1, S_max=100, print_every=None)
    reference_xi = torch.as_tensor(reference["xi_draws"], device=DEVICE, dtype=X_old.dtype)
    rows = []
    for label, out in historical_runs.items():
        recovered = metric.evaluate_bnn(out["model"].decoder, out["xi"], splits_old["X_test"], signal_old_split["y_test"], info_old,
                                        reference_decoder=reference_model.decoder, reference_xi=reference_xi)
        rows.append({"configuration": label, "Active SKL": recovered["active_skl"], "Zero JS": recovered["zero_js"]})
    display(pd.DataFrame(rows).set_index("configuration").round(4))